apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: flask-app
type: Opaque
data:
  POSTGRES_DB: bXlkYg==        # mydb en base64
  POSTGRES_USER: bXl1c2Vy      # myuser en base64
  POSTGRES_PASSWORD: cGFzczEyMzQ= # pass1234 en base64

